Checkbox
js-tasks-ru/htmlcss-20220317_studilovvlad pull request #17
Opened 2022-04-26 03:15 UTC by Abbie63

2022-04-26 03:16 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-26 03:23 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-26 03:38 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-30 10:19 UTC, GSemikozov requested changes

2022-04-30 10:19 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +.container {
ой, а что это за контейнер внутри компонента .checkbox?) удалим

2022-04-30 10:23 UTC, GSemikozov requested changes

2022-04-30 10:23 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox__header {
элемент не может быть родителем своего родителя - удалим

2022-05-12 14:34 UTC, GSemikozov approved these changes

2022-05-12 14:34 UTC, merged