Toggler
js-tasks-ru/htmlcss-20220317_studilovvlad pull request #19
Opened 2022-04-26 04:28 UTC by Abbie63

2022-04-26 04:29 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-30 10:22 UTC, GSemikozov requested changes

2022-04-30 10:22 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +.toggler__header {
элемент не может быть родителем своего родителя - удалим

2022-04-30 10:22 UTC, GSemikozov requested changes

2022-04-30 10:22 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +.container {
удалим

2022-05-12 14:35 UTC, GSemikozov approved these changes

2022-05-12 14:35 UTC, merged