edited  solution for 2-2
js-tasks-ru/htmlcss-20220317_studilovvlad pull request #3
Opened 2022-03-27 20:12 UTC by Abbie63

2022-03-27 20:12 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-28 20:31 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-03-29 19:25 UTC, GSemikozov requested changes

2022-03-29 19:25 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    overflow: auto;
точно будет лишним - нам не нужен скролл внутри компонента, даже потенциально)

2022-03-29 19:25 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
это тоже лишнее, на мобилке будет плохо

2022-03-29 19:25 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    list-style-position: inside;
list-style тоже не нужен

2022-03-29 19:25 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    border: 1px solid var(--grey-3)
на этом уровне удобно задать общие для других дочерних элементов паддинги

2022-03-29 19:25 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__item:not([open]) {
все что здесь описано - лишнее, фиксировать размеры и задавать позиционирование не надо

2022-03-29 19:25 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    display: inline;
block

2022-03-29 19:25 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding-top: 24px;
вместо паддингов здесь удобнее задать общие на уровне .accordion__item, а отступ между summary и текстом - можно уже решать например на уровне текста

2022-03-29 19:25 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +        <div class = "accordion__parent">
accordion__parent -> parent это элемент аккордиона, но никак не его родитель

2022-03-29 19:25 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +            <details class = "accordion accordion__item" open>
элементы блока - всегда его дочерние элементы и не могут задаваться на одном уровне

2022-03-29 19:25 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +                <summary class = "accordion accordion__summary">
а зачем здесь класс accordion?

2022-03-29 19:25 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +                <summary class = "accordion accordion__summary">
и везде ниже у элементов

2022-03-30 15:41 UTC, Abbie63 commented on 03-lection1/02-accordion/index.html
> +                <summary class = "accordion accordion__summary">
Я хотел задать общие параметры, но не понадобилось

2022-03-30 15:42 UTC, Abbie63 commented on 03-lection1/02-accordion/index.html
> +            <details class = "accordion accordion__item" open>
Прошу прощения, можно чуть-чуть конкретнее? Я имею в виду, что конкретно здесь не так?

2022-03-30 16:16 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-30 18:41 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +            <details class = "accordion accordion__item" open>
было максимально конкретно)
все элементы блока accordion должны быть вложены в него, и ни в коем случае не располагаться на одном уровне (как здесь - "accordion accordion__item")

2022-03-30 18:41 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +                <summary class = "accordion accordion__summary">
класс блока всегда один и задается на верхнем уровне компонента, и больше не дублируется внутри

2022-03-30 18:58 UTC, GSemikozov requested changes

2022-03-30 18:58 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding-top: 8px;
это получается лишнее?

2022-03-30 18:58 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin-right: 2%;
одновременно и паддинги и марджины?
паддинги - это внутренние отступы, они нас и интересуют. Рекомендую указывать в пикселях как это задано в макете.

2022-03-30 18:58 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding-right: 70%;
кажется лишним такой огромный паддинг. Паддинг слева = паддинг справа

2022-03-30 18:58 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin-bottom: 8px;
опять - сверху паддинг, снизу - марджин)
думаю, если указать общие отступы на уровне .accordion__item, то в .accordion__text и .accordion__summary вряд ли потребуется что-то указывать дополнительно (разве что отступ между ними самими)

2022-03-30 18:58 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +                <summary class = "accordion accordion__summary">
.block
    .block_modifier1
    .block_modifier2
    .block__element1
    .block__element2
    .block__element2_modifier
    etc

2022-03-30 22:07 UTC, Abbie63 commented on 03-lection1/02-accordion/accordion.css
> +    padding-top: 8px;
Без паддинга тут отступа сверху нет и выглядит так себе

2022-03-30 22:12 UTC, Abbie63 commented on 03-lection1/02-accordion/accordion.css
> +    margin-right: 2%;
Постарался убрать лишнее, ставлю в некоторых местах проценты из расчета на то, чтобы под экран подстраивалось, но пока что иногда в попытках сделать красиво лишнего добавляю, пытаюсь это исправить

2022-03-30 22:13 UTC, Abbie63 commented on 03-lection1/02-accordion/accordion.css
> +    padding-right: 70%;
Ой, это остатки с того момента, когда я экспериментировал с паддингами, прошу прощения

2022-03-30 22:15 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-31 14:39 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding-top: 8px;
главное чтобы соответствовало дизайну, наши личные вкусовые качества - не в счет)

2022-03-31 14:40 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin-right: 2%;
подстраивать лучше другим способом - давать возможность блоку растягиваться / сужаться не разваливая верстку. А тему паддингов через относительные единицы разберем через 1 занятие

2022-03-31 14:41 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin-right: 2%;
"стараться сделать красиво" не нужно, нужно сделать максимально как в дизайне)

2022-03-31 14:42 UTC, GSemikozov requested changes

2022-03-31 14:42 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding-left: 5%;
я думаю паддинги здесь вообще не нужны - мы ведь их задаем на уровне видимой части компонента - .accordion__item
<img width="205" alt="Screenshot 2022-03-31 at 17 42 33" src="https://user-images.githubusercontent.com/6191270/161082562-21ea5598-1713-4560-b762-3c5983fbe2f8.png">

2022-04-01 19:49 UTC, Abbie63 commented on 03-lection1/02-accordion/accordion.css
> +    padding-top: 8px;
На уровне суммари задавать отступ? В шаблоне ведь он имеется

2022-04-01 20:01 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-01 20:10 UTC, GSemikozov requested changes

2022-04-01 20:10 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__summary {
для .accordion__summary и .accordion__text надо еще описать стили для текста

2022-04-02 18:14 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-03 19:26 UTC, GSemikozov approved these changes

2022-04-03 19:26 UTC, merged