Histogram
js-tasks-ru/htmlcss-20220317_studilovvlad pull request #4
Opened 2022-04-03 06:59 UTC by Abbie63

2022-04-03 07:00 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-03 07:05 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-03 19:30 UTC, GSemikozov requested changes

2022-04-03 19:30 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    flex-direction: column;
здесь нужно задать общие для блока паддинги

2022-04-03 19:30 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 59px;
не стоит фиксировать, длина контента внутри может быть разной

2022-04-03 19:30 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin-right: 24px;
чтобы не задавать каждому элементу подобные паддинги (чтобы оттолкнуться от границ блока, а не отодвинуться от соседних элементов) - нужно на уровне блока задать общие паддинги

2022-04-03 19:30 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    display: block;
по умолчанию и так block)

2022-04-03 19:30 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__header__text {
элемент элемента? такая запись будет ошибкой, нужно просто .histogram__header-text

2022-04-07 19:54 UTC, GSemikozov approved these changes

2022-04-07 19:54 UTC, merged