Skeleton
js-tasks-ru/htmlcss-20220317_studilovvlad pull request #7
Opened 2022-04-06 01:00 UTC by Abbie63

2022-04-06 01:01 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-06 18:45 UTC, GSemikozov requested changes

2022-04-06 18:45 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    flex-direction: column;
не хватает общих паддингов

2022-04-06 18:45 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    margin-left: 24px;
чтобы у каждого дочернего элемента не указывать такие марджины, которые нужны лишь чтобы оттолкнуться от границ блока - лучше задать 1 раз паддинги на уровне самого блока

2022-04-06 18:45 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__header__lines {
.skeleton__header__lines -> .skeleton__header-lines

2022-04-06 18:45 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__header__avatar {
.skeleton__avatar

2022-04-06 18:45 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.line_1 {
.line_1 => .skeleton__line_small и далее по списку ниже )

2022-04-06 18:45 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.line_3:last-child {
всегда ли и во всех ли ситуациях для этого типа линии - если она последняя - нужен этот марджин? точно нет, особенно с четом того что вместо этого марджина мы зададим паддинг на уровне блока)

2022-04-06 18:45 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.line_3:last-child {
в общем, лучше найти другой спосок расставить отступы, например через родителя и gap. И то же самое касается и .line_1

2022-04-07 05:03 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-07 05:31 UTC, Abbie63 commented on 04-lection2/02-skeleton/skeleton.css
> +.line_3:last-child {
Исправил. Пытался еще уменьшить количество блоков, но зашел в тупик. Благо, сделал сейв кода и быстро вернул как было)

2022-04-07 05:32 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-08 09:40 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-08 13:42 UTC, GSemikozov requested changes

2022-04-08 13:42 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 59px;
фиксировать надо, текст ведь может быть разный

2022-04-08 13:42 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin-left: 26px;
вместо таких мерджинов лучше задать общий паддинг на уровне блока

2022-04-08 13:42 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__header__text {
.histogram__header__text -> .histogram__header-text

2022-04-09 06:26 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-09 18:37 UTC, GSemikozov approved these changes

2022-04-09 18:37 UTC, merged