Cards
js-tasks-ru/htmlcss-20220317_studilovvlad pull request #8
Opened 2022-04-09 07:13 UTC by Abbie63

2022-04-09 07:19 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-09 18:44 UTC, GSemikozov requested changes

2022-04-09 18:44 UTC, GSemikozov commented on components/cards.css
> +.main {
в блоке cards сразу 3 сторонних блока - .main, .card, .card-container. Судя по названию здесь должен быть блок .cards. Надо поправить.

.card-container - удалить все эти странные паддинги и завернуть в .container как мы это делали на занятии - этого будет достаточно.

2022-04-09 18:44 UTC, GSemikozov commented on components/footer.css
> +    height: 384px;
высоту фиксировать не надо

2022-04-09 18:44 UTC, GSemikozov commented on components/footer.css
> +    margin-left: 28%;
такой вариант подойдет только для десктопа. Вместо этого - завернуть текст в фктере в .container + комкретно для текста ограничить ширину max-width: 640px + выравниваем по центру margin: 0 auto

2022-04-09 18:44 UTC, GSemikozov commented on components/header.css
> +    margin-left: 11%;
ни в коем случае. Нужно завернуть содержимое хедера в контейнер

2022-04-09 18:44 UTC, GSemikozov commented on components/header.css
> +    height: 237px;
не фиксируем

2022-04-09 18:44 UTC, GSemikozov commented on components/header.css
> +    margin-top: 96px;
ни в коем случае - это ведь компонент верхнего уровня. Если использовать марджин - сам компонент будет ниже на эту величину. Чтобы понять последствия - можно задать фон body синий, а у хедера оставить белый

2022-04-09 18:44 UTC, GSemikozov commented on components/histogram.css
> +.histogram {
это проверяем в рамках текущего ПР?

2022-04-10 08:23 UTC, Abbie63 commented on components/histogram.css
> +.histogram {
Я создал копию гистограммы в репозитории с компонентами, по сути там последняя версия гистограммы

2022-04-10 08:27 UTC, Abbie63 commented on components/cards.css
> +.main {
Я назвал кардс из-за боязни конфликтов, думал, что хедер и футер можно использовать повторно, а для мейна дал название по сути самого задания, чтобы затем не путаться если придется делать что-то с другим мейном)

2022-04-10 08:54 UTC, Abbie63 commented on components/histogram.css
> +.histogram {
Ну и сейчас переделывая добавил туда некоторые моменты

2022-04-10 09:09 UTC, Abbie63 commented on components/cards.css
> +.main {
Попробовал переместить в контейнер пересмотрев поверхностно тот урок. Если всё еще не так, как надо - пересмотрю полностью, просто сегодня планировал еще предыдущие два урока пересмотреть перед тем, как к следующей домашке преступать)

2022-04-11 12:08 UTC, GSemikozov commented on components/histogram.css
> +.histogram {
то есть проверять?)

2022-04-11 12:10 UTC, GSemikozov requested changes

2022-04-11 12:10 UTC, GSemikozov commented on components/histogram.css
> +    margin-left: 26px;
марджины на уровне блока все равно нельзя

2022-04-11 12:10 UTC, GSemikozov commented on components/cards.css
> +.main {
тут пока комментарий актуален - указанные блоки не реализованы ка боки и до сих пор описаны в этом одном файле

2022-04-13 16:06 UTC, Abbie63 commented on components/histogram.css
> +.histogram {
Наверное, но это же лишнее время на проверку. Вроде как разница с основной гистограммой с 78 строки начинается

2022-04-13 20:41 UTC, GSemikozov requested changes

2022-04-13 20:41 UTC, GSemikozov commented on components/container.css
> +    padding-left: 11.5%;
все паддинги удалить и заменить на max-width: 1110px; margin: 0 auto;

2022-04-13 20:41 UTC, GSemikozov commented on components/header.css
> +.header__container {
выше уже есть контейнер который ограничивает по ширине, а паддинги можно задать пока на уровне блока .header

2022-04-15 20:08 UTC, GSemikozov requested changes

2022-04-15 20:08 UTC, GSemikozov commented on components/container.css
> +    padding-top: 68px;
паддинги нужны как я понимаю только в одном конкретном случае, а не во всех случаях использования контейнера, верно? и скорее всего они относятся к .main или .cards

2022-04-15 20:08 UTC, GSemikozov commented on components/cards-main.css
> +.main {
блок называется cards-main - надо либо класс поправить, либо название блока

2022-04-15 20:08 UTC, GSemikozov commented on components/header.css
> +    padding-left: 160px;
если будет использовать контейнер для оборачивания контента - тогда это паддинг не нужен будет

2022-04-17 17:57 UTC, Abbie63 commented on components/header.css
> +    padding-left: 160px;
А как тогда с отступами быть?

2022-04-17 19:07 UTC, GSemikozov commented on components/header.css
> +    padding-left: 160px;
структура должна быть такой
```
header
    container
        header__inner
```
а класс таким
```
.header { padding: 96px 0 77px; }

```

2022-04-18 14:24 UTC, GSemikozov requested changes

2022-04-18 14:24 UTC, GSemikozov commented on components/header.css
> +    padding-left: 12%;
вместо такого паддинга, повторюсь, нужно завернуть содержимое в общий .container (либо класс оставляем как есть, но - стили будут такими же: `max-width: 1110px; margin: 0 auto`)

2022-04-18 15:09 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-19 20:17 UTC, GSemikozov approved these changes

2022-04-19 20:17 UTC, merged