calendar
js-tasks-ru/htmlcss-20220317_studilovvlad pull request #9
Opened 2022-04-10 13:01 UTC by Abbie63

2022-04-10 13:01 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-11 12:15 UTC, GSemikozov requested changes

2022-04-11 12:15 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.container {
это просто вспомогательный контейнер? блока .container тут недостаточно?

в любом случае такие стили - вне БЭМ, их нельзя описывать в компоненте. Можно на странице с решением задачи прямо в теге style

2022-04-11 12:15 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    height: 270px;
ширину и высоту не фиксируем, максимум - max-width как в дизайне

2022-04-11 12:15 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.calendar__item_day {
это наверно .calendar__item, а не модификатор .calendar__item_day?

2022-04-11 12:15 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    padding-top: 16px;
если не используем паттерн с padding-bottom: 100%, то этот враппер - лишний, можно удалить

2022-04-11 12:15 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.active {
модификатор дня? .calendar__item_active

2022-04-11 12:15 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.between {
.calendar__item_between

2022-04-13 15:57 UTC, Abbie63 commented on 05-lection3/03-calendar/calendar.css
> +.calendar__item_day {
В макете разные шрифты у дней недели и дней месяца. Но я поправил, убрав общее

2022-04-13 15:58 UTC, Abbie63 commented on 05-lection3/03-calendar/calendar.css
> +    padding-top: 16px;
Когда убрал фиксированные размеры - пришлось всё-таки использовать)

2022-04-13 20:37 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.calendar__item_day {
то что разное меняем модификаторами

2022-04-13 20:39 UTC, GSemikozov requested changes

2022-04-13 20:39 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    grid-template-columns: repeat(7, 36px);
неа, вместо 36px надо 1fr )

2022-04-13 20:39 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    max-height: 270px;
max-height + max-width здесь лишние (можно один раз на уровне всего блока 1 раз ограничить по ширина сам блок)

2022-04-15 17:37 UTC, Abbie63 commented on 05-lection3/03-calendar/calendar.css
> +.calendar__item_day {
Но разве _day не модификатор?

2022-04-15 17:39 UTC, Abbie63 commented on 05-lection3/03-calendar/calendar.css
> +    grid-template-columns: repeat(7, 36px);
Заменил, но только у столбцов. Если поставить и у строк - всё ломается

2022-04-15 17:42 UTC, Abbie63 commented on 05-lection3/03-calendar/calendar.css
> +    max-height: 270px;
Так?

2022-04-15 20:10 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.calendar__item_day {
а что конкретно он модифицирует? Модификатор это всегда часть элемента или блока, который он модифицирует. В данном случае я не вижу что именно модифицирует .calendar__item_day - скорее, как я написал выше, здесь подразумевалось описывать именно элемент )

2022-04-15 20:11 UTC, GSemikozov approved these changes

2022-04-15 20:11 UTC, merged